### ISSUE TITLE
Util.tree ?element function example inconsistent with its signature in the documentation (?)

### ISSUE THREAD

**Issue by OndrejPopp** [aantron/markup.ml#61] opened 2020-11-26 14:13 UTC
Hello Anton,
I have just been reading about the parser documentation and it appears to me that the application of the element function is inconsistent with its signature,

So,
?element:(name -> (name * string) list -> 'a list -> 'a) 
is a function of three arguments producing 'a

but it is used as,
~element:(fun (name, _) children -> Element (name, children))

which appears to be a function of only two arguments, the tupple (name, _) and children,

See here for the original piece of documentation,
kind regards,
Ondrej

val tree : 
       ?text:(string list -> 'a) ->
       ?element:(name -> (name * string) list -> 'a list -> 'a) ->
       ?comment:(string -> 'a) ->
       ?pi:(string -> string -> 'a) ->
       ?xml:(xml_declaration -> 'a) ->
       ?doctype:(doctype -> 'a) ->
       ([< signal ], sync) stream -> 'a option
This function's type signature may look intimidating, but it is actually easy to use. It is best introduced by example:
type my_dom = Text of string | Element of name * my_dom list

"<p>HTML5 is <em>easy</em> to parse".  
|> string
|> parse_html
|> signals
|> tree
  ~text:(fun ss -> Text (String.concat "" ss))
  ~element:(fun (name, _) children -> Element (name, children))

**Comment by aantron** [comment] 2020-11-26 16:16
This was actually fixed in #50, and is now

https://github.com/aantron/markup.ml/blob/e1aed3c90cb564c261d4fe4bc272f918f9113039/src/markup.mli#L554-L561

The issue is that Markup.ml's doc generation script is currently broken, and as I haven't gotten around to fixing it, I haven't been able to post accurate docs lately (almost all the docs are still accurate, though). I opened #62 to remind myself to get on it! I'm closing this issue in the meantime.

**Closed by aantron** 2020-11-26 16:16 UTC

**Comment by OndrejPopp** [comment] 2020-11-26 21:25
Ok, tx Anton! 😃
